apiVersion: v1
kind: Secret
metadata:
  name: azdevops
data:
  AZP_TOKEN: <azure-devops-pat-token>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: <image-referrence>
        env:
          - name: AZP_URL
            value: <azure-devops-url>
          - name: AZP_POOL
            value: <azure-devops-pool-name>
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN